language: python
sudo: false
python:
  - "2.7"
  - "3.5"
  - "3.6"
env:
  matrix:
    - OPTIONAL_DEPS=true
    - OPTIONAL_DEPS=false
install:
  - pip install -U coveralls pytest
  - if [ "$OPTIONAL_DEPS" = true ]; then pip install -U pandas; fi
script:
  - coverage run --source=pubchempy -m pytest
after_success:
  - coveralls
